import { useState } from 'react';
import { FlatList, Modal, Pressable, StyleSheet, Text, View } from 'react-native';

import { LICENSE_TEXTS, OPEN_SOURCE_PACKAGES } from '../content/licenses.generated';
import { colors, fonts, radius, spacing } from '../theme';
import { GoldButton } from './GoldButton';

/** Open-source notices of the code and files shipped in the app (generated by scripts/generate-licenses.cjs). */
export function LicensesModal({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const [open, setOpen] = useState<string | null>(null);
  return (
    <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}>
      <View style={styles.screen}>
        <FlatList
          data={OPEN_SOURCE_PACKAGES}
          keyExtractor={(p) => `${p.name}@${p.version}`}
          contentContainerStyle={styles.content}
          ListHeaderComponent={
            <View style={styles.header}>
              <Text style={styles.title}>Open-source licenses</Text>
              <Text style={styles.muted}>Calincr is built with these open-source projects. Tap one to read its license.</Text>
            </View>
          }
          renderItem={({ item }) => {
            const key = `${item.name}@${item.version}`;
            const expanded = open === key;
            return (
              <Pressable
                onPress={() => setOpen(expanded ? null : key)}
                accessibilityRole="button"
                accessibilityState={{ expanded }}
                style={styles.item}
              >
                <Text style={styles.name}>
                  {item.name} <Text style={styles.muted}>{item.version}</Text>
                </Text>
                <Text style={styles.muted}>{item.license}</Text>
                {expanded ? <Text style={styles.text}>{LICENSE_TEXTS[item.text]}</Text> : null}
              </Pressable>
            );
          }}
        />
        <GoldButton label="Close" onPress={onClose} style={styles.close} />
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background, paddingBottom: spacing.xl },
  content: { padding: spacing.lg, gap: spacing.sm },
  header: { gap: spacing.xs, marginBottom: spacing.sm },
  title: { color: colors.parchment, fontFamily: fonts.titleBold, fontSize: 24 },
  item: { backgroundColor: colors.stone, borderRadius: radius.md, padding: spacing.md, gap: 4 },
  name: { color: colors.text, fontFamily: fonts.title, fontSize: 14 },
  text: { color: colors.text, fontSize: 12, lineHeight: 17, marginTop: spacing.xs },
  muted: { color: colors.textMuted, fontSize: 12 },
  close: { marginHorizontal: spacing.lg },
});
